name: 'Deploy for Vercel'
description: 'Deploy preview and production environments to Vercel'
author: 'W3Dev'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  vercel_token:
    description: 'Vercel API token'
    required: true
  vercel_org_id:
    description: 'Vercel Organization/Team ID'
    required: true
  vercel_project_id:
    description: 'Vercel Project ID'
    required: true
  vercel_project_name:
    description: 'Vercel Project name (for linking)'
    required: false
    default: ''
  package_manager:
    description: 'Package manager to use (bun, npm, pnpm)'
    required: false
    default: 'bun'
  node_version:
    description: 'Node.js version'
    required: false
    default: '22'
  working_directory:
    description: 'Working directory for the build'
    required: false
    default: '.'
  alias_prefix:
    description: 'Prefix for preview alias (e.g., "myapp" creates pr-123--myapp.vercel.app)'
    required: false
    default: ''
  prebuild_script:
    description: 'Optional script to run before build (e.g., configure git author)'
    required: false
    default: ''
  install_command:
    description: 'Custom install command (overrides package_manager default)'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}
  environment:
    description: 'Deployment environment (preview or production)'
    required: false
    default: 'preview'
  predeploy_script:
    description: 'Optional script to run before deployment'
    required: false
    default: ''

outputs:
  deployment_url:
    description: 'The Vercel deployment URL'
    value: ${{ steps.deploy.outputs.url }}
  alias_url:
    description: 'The aliased preview URL'
    value: ${{ steps.deploy.outputs.alias_url }}
  pr_number:
    description: 'The PR number (if applicable)'
    value: ${{ steps.context.outputs.pr_number }}

runs:
  using: 'composite'
  steps:
    - name: Determine context
      id: context
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        echo "is_production=${{ inputs.environment == 'production' }}" >> $GITHUB_OUTPUT

        # Skip alias generation for production deployments
        if [ "$ENVIRONMENT" == "production" ]; then
          echo "pr_number=" >> $GITHUB_OUTPUT
          echo "preview_alias=" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          if [ -n "${{ github.event.inputs.pr_number }}" ]; then
            echo "pr_number=${{ github.event.inputs.pr_number }}" >> $GITHUB_OUTPUT
            echo "preview_alias=pr-${{ github.event.inputs.pr_number }}--${{ inputs.alias_prefix }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=" >> $GITHUB_OUTPUT
            echo "preview_alias=" >> $GITHUB_OUTPUT
          fi
        else
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          if [ -n "${{ inputs.alias_prefix }}" ]; then
            echo "preview_alias=pr-${{ github.event.pull_request.number }}--${{ inputs.alias_prefix }}" >> $GITHUB_OUTPUT
          else
            echo "preview_alias=" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Setup Bun
      if: inputs.package_manager == 'bun'
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup pnpm
      if: inputs.package_manager == 'pnpm'
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        INSTALL_CMD: ${{ inputs.install_command }}
        PKG_MANAGER: ${{ inputs.package_manager }}
      run: |
        if [ -n "$INSTALL_CMD" ]; then
          eval "$INSTALL_CMD"
        elif [ "$PKG_MANAGER" == "bun" ]; then
          bun install
        elif [ "$PKG_MANAGER" == "pnpm" ]; then
          pnpm install
        else
          npm ci
        fi

    - name: Install Vercel CLI
      shell: bash
      env:
        PKG_MANAGER: ${{ inputs.package_manager }}
      run: |
        if [ "$PKG_MANAGER" == "bun" ]; then
          bun install -g vercel
        elif [ "$PKG_MANAGER" == "pnpm" ]; then
          pnpm install -g vercel
        else
          npm install -g vercel
        fi

    - name: Run prebuild script
      if: inputs.prebuild_script != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: ${{ inputs.prebuild_script }}

    - name: Setup Vercel project linking
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        PROJECT_NAME: ${{ inputs.vercel_project_name }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        rm -rf .vercel
        mkdir -p .vercel
        FINAL_NAME="${PROJECT_NAME:-$REPO_NAME}"
        echo "{\"orgId\":\"$VERCEL_ORG_ID\",\"projectId\":\"$VERCEL_PROJECT_ID\",\"projectName\":\"$FINAL_NAME\"}" > .vercel/project.json
        cat .vercel/project.json

    - name: Pull Vercel environment
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_TOKEN: ${{ inputs.vercel_token }}
      run: vercel pull --yes --environment=${{ inputs.environment }} --token=$VERCEL_TOKEN

    - name: Build with Vercel
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_TOKEN: ${{ inputs.vercel_token }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$ENVIRONMENT" == "production" ]; then
          vercel build --prod --token=$VERCEL_TOKEN
        else
          vercel build --token=$VERCEL_TOKEN
        fi

    - name: Run predeploy script
      if: inputs.predeploy_script != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: ${{ inputs.predeploy_script }}

    - name: Deploy to Vercel
      id: deploy
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_TOKEN: ${{ inputs.vercel_token }}
        PREVIEW_ALIAS: ${{ steps.context.outputs.preview_alias }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$ENVIRONMENT" == "production" ]; then
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN)
        else
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)
        fi
        echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

        if [ -n "$PREVIEW_ALIAS" ]; then
          vercel alias set "$DEPLOYMENT_URL" "$PREVIEW_ALIAS" --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID || true
          echo "alias_url=https://${PREVIEW_ALIAS}.vercel.app" >> $GITHUB_OUTPUT
        fi

    - name: Add deployment summary
      shell: bash
      env:
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.url }}
        ALIAS_URL: ${{ steps.deploy.outputs.alias_url }}
        COMMIT_SHA: ${{ github.sha }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$ENVIRONMENT" == "production" ]; then
          echo "## ✅ Vercel Production Deployed" >> $GITHUB_STEP_SUMMARY
        else
          echo "## ✅ Vercel Preview Deployed" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| | |" >> $GITHUB_STEP_SUMMARY
        echo "|---|---|" >> $GITHUB_STEP_SUMMARY
        echo "| **Deployment URL** | $DEPLOYMENT_URL |" >> $GITHUB_STEP_SUMMARY
        if [ -n "$ALIAS_URL" ]; then
          echo "| **Alias URL** | $ALIAS_URL |" >> $GITHUB_STEP_SUMMARY
        fi
        echo "| **Commit** | \`$COMMIT_SHA\` |" >> $GITHUB_STEP_SUMMARY

    - name: Comment on PR
      if: steps.context.outputs.pr_number != '' && inputs.environment != 'production'
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ steps.context.outputs.pr_number }}
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.url }}
        ALIAS_URL: ${{ steps.deploy.outputs.alias_url }}
        PROJECT_NAME: ${{ inputs.vercel_project_name }}
        REPO_NAME: ${{ github.event.repository.name }}
        COMMIT_SHA: ${{ github.sha }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = parseInt(process.env.PR_NUMBER);
          const deploymentUrl = process.env.DEPLOYMENT_URL;
          const aliasUrl = process.env.ALIAS_URL;
          const projectName = process.env.PROJECT_NAME || process.env.REPO_NAME;
          const commitSha = process.env.COMMIT_SHA;
          const marker = `<!-- vercel-preview-${projectName} -->`;
          
          const commentBody = `${marker}

          🚀 **Preview Deployed!**

          | | |
          |---|---|
          | **Preview URL** | ${deploymentUrl} |
          ${aliasUrl ? `| **Alias URL** | ${aliasUrl} |` : ''}
          | **Commit** | \`${commitSha}\` |
          `;
          
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            per_page: 100
          });
          
          const existingComment = comments.find(comment => 
            comment.user.login === 'github-actions[bot]' && 
            comment.body.includes(marker)
          );
          
          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: commentBody
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          }
